### ISSUE TITLE
Add GitHub Issue Template for Structured Stories

### ISSUE THREAD

**Issue by plva** [plva/econexyz#107]
### Goal

Give every contributor a ready-made Markdown form that matches our **Story** house style—header, goal, phases, work items, acceptance, dependencies, and (optional) ADR stub—so that new backlog items stay consistent and review overhead stays low.

| Phase  | Purpose                                                                            | Surfaces touched                             |
| ------ | ---------------------------------------------------------------------------------- | -------------------------------------------- |
| **P0** | Ship the template file, reference it from docs                                     | `.github/ISSUE_TEMPLATE/`, `CONTRIBUTING.md` |
| **P1** | Auto-label incoming story issues & guard empty sections via a lightweight CI check | GitHub Actions, label set                    |

---

#### P0 Work items

* Create `.github/ISSUE_TEMPLATE/story.yml` (YAML-front-matter style) that renders a **Markdown body** pre-filled like:

  ```yaml
  name: 📝 Story
  description: Carve work into P0 / P1 units with acceptance checks
  labels: ["story", "triage"]
  body:
    - type: markdown
      attributes:
        value: |
          ## STORY — <Action>

          ### Goal
          <why we need it>

          | Phase | Purpose |
          |-------|---------|
          | P0 | ... |
          | P1 | ... |

          #### P0 Work items
          - …

          #### P0 Acceptance
          - …

          #### P1 Work items
          - …

          #### P1 Acceptance
          - …

          **Dependencies**: …

          <!-- Optional: uncomment if this story introduces a new strategic choice -->
          <!--
          ### Requires ADR
          *Title idea*: <short phrase>  
          *Rationale*: <1-2 sentences>
          -->
  ```

* Add a short **“Story template”** subsection to `CONTRIBUTING.md`, linking to the file and reminding authors to keep each story self-contained.

* **Commit message**

  ```
  docs(templates): add GitHub issue template for structured stories
  ```

#### P0 Acceptance ✓

* The **Issues → New Issue** screen shows “📝 Story” with the correct scaffold.
* Opening the template locally renders the table and code blocks without layout glitches.
* `CONTRIBUTING.md` points to the template and explains when to use it.

---

#### P1 Work items

* Extend existing **Labeler action** (ADR 0019) or add a tiny workflow `.github/workflows/story-lint.yml` that:

  1. Triggers on `issues.opened`.
  2. Adds label `needs-sections` if the issue body lacks any of the mandatory H3 headings (`### Goal`, `#### P0 Work items`, etc.).
     *Use simple `grep -E` logic inside `actions/github-script` to stay dependency-free.*
* Update label docs in ADR 0019 with the new `needs-sections` semantics.
* **Commit message**

  ```
  ci(labels): auto-flag story issues missing required sections
  ```

#### P1 Acceptance ✓

* Creating a new issue without the headings immediately applies `needs-sections`; one with all headings does not.
* ADR 0019 diff lists the new label and its purpose.
* The workflow is green on CI lint runs (`act` or real PR).

---

**Dependencies**

* **ADR 0007 – Contributor Experience Kit** (template placement & docs)
* **ADR 0019 – GitHub Label Strategy** (for consistent auto-labels)

*(No new ADR required; template follows established contributor-experience conventions.)*
