### ISSUE TITLE
Parameterize GitHub Actions for Owner / Repo

### ISSUE THREAD

**Issue by plva** [plva/econexyz#142]
### Goal

Centralize the GitHub username (`plva`) and repository name (`econexyz`) in one base configuration so every workflow references a single source of truth, paving the way for future cookiecutter templating.

---

### Breakdown Strategy

**Two phases (p0 → p1)** cleanly separate config scaffolding from workflow migration.

|Phase|Purpose|Deliverables|
|---|---|---|
|**p0 – base-config scaffold**|Introduce a canonical place for owner / repo settings.|• New base config file• Utility composite / reusable workflow to surface vars|
|**p1 – workflow refactor**|Update existing CI workflows to consume the centralized variables.|• All `.github/workflows/*.yml` updated• PR validation|

---

#### Work items

- **feat(ci): add repo-vars file**  
    Create `.github/repo_vars.yml` (or `cookiecutter.json` if aligning with cookiecutter) containing:
    
    ```yaml
    owner: plva
    repo: econexyz
    ```
    
- **feat(ci): expose vars via composite workflow**  
    `.github/workflows/_setup-repo-vars.yml`
    
    ```yaml
    name: repo-vars
    on: [workflow_call]
    outputs:
      owner:
        value: ${{ inputs.owner }}
      repo:
        value: ${{ inputs.repo }}
    inputs:
      owner:
        required: true
      repo:
        required: true
    runs:
      using: "composite"
      steps:
        - run: echo "owner=${{ inputs.owner }}" >> $GITHUB_OUTPUT
        - run: echo "repo=${{ inputs.repo }}"  >> $GITHUB_OUTPUT
    ```
    
- **docs(readme): explain base config & future cookiecutter usage**
    

#### Acceptance checklist

-  `repo_vars.yml` checked in with correct owner / repo.
    
-  Composite workflow outputs `owner` and `repo` when called in a test workflow (`act` or GH run).
    
-  README documents how to adjust vars for forks/templates.
    

---

#### Work items

- **ci(docs): migrate docs workflow**  
    Replace hard-coded `plva/econexyz` with calls to `_setup-repo-vars`.
    
    ```yaml
    jobs:
      build:
        uses: ./.github/workflows/_setup-repo-vars.yml
        with:
          owner: ${{ vars.REPO_OWNER }}   # or from repo_vars.yml via step
          repo:  ${{ vars.REPO_NAME }}
    ```
    
    Then reference `${{ needs.build.outputs.owner }}` and `${{ needs.build.outputs.repo }}` everywhere instead of literals.
    
- **ci(test): migrate other workflows (lint, test, release, etc.)**  
    Ensure all `uses: actions/checkout@…` `repository: owner/repo` or similar lines consume the outputs.
    
- **chore: remove residual hard-coded strings**  
    Grep for `plva` and `econexyz`; update or document intentional occurrences (e.g., README badges).
    
- **docs(readme): note templated vars in workflow snippets**.
    

#### Acceptance checklist

-  All YAML workflows lint successfully (`act` or `actionlint`).
    
-  `grep -R --line-number -E 'plva|econexyz' .github/workflows` shows only intentional references in the base-config file.
    
-  CI pipelines (docs, tests, etc.) still pass on PR.
    
-  README badge links still resolve to `https://github.com/plva/econexyz/actions`.
    

---

### Dependencies

p1 requires p0 merged.

---

### Commit Guidelines (examples)

|Phase|Commit header|Notes|
|---|---|---|
|p0|**feat(ci): add repo-vars config & composite workflow**|new scaffolding|
|p0|**docs(readme): document owner/repo parameterization**|README|
|p1|**ci: refactor docs workflow to use repo-vars**|first workflow migrated|
|p1|**ci: migrate remaining workflows to repo-vars**|bulk refs removed|
|p1|**chore: purge hard-coded owner/repo refs**|cleanup|

---

### Reviewer Notes

After p1, changing `repo_vars.yml` (or its future cookiecutter equivalent) should be the _only_ step required to fork / template the project for a new owner or repo, keeping the repository cookiecutter-ready.
