### ISSUE TITLE
Publish Sphinx-generated docs on GitHub Pages

### ISSUE THREAD

**Issue by plva** [plva/econexyz#58]
### Goal

Host project documentation at `https://<org>.github.io/<repo>` using Sphinx, MyST-Parser (Markdown support), and the Furo theme (fallback to Sphinx default if Furo is absent), with automatic deployment from `main` via GitHub Pages.

---

### Breakdown Strategy

A **two-phase** plan—**p0 → p1**—keeps work atomic and reviewable:

|Phase|Purpose|Deliverables|
|---|---|---|
|**p0 – foundations**|Let contributors build docs locally.|• Doc dependencies• Minimal `docs/` tree & config• Nox `docs` session• README local-build instructions|
|**p1 – continuous deployment**|Automate building & publishing docs on every push/tag.|• GitHub Actions workflow• Docs badge/link in README• Manual repo-settings step to enable Pages|

---

#### Work items

- **build(deps): add doc extras** — add optional `docs` extras to `pyproject.toml` (Sphinx, MyST-Parser, optional Furo).
    
- **feat(docs): scaffold minimal Sphinx tree** — create `docs/conf.py` (conditional Furo) and `docs/index.md` (“Hello, Docs!”).
    
- **chore(nox): add `docs` session** – install extras and run `sphinx-build -M html docs docs/_build`.
    
- **docs(readme): document local docs build** – add `nox -s docs` one-liner.
    

#### Acceptance checklist

-  `uv pip install -e .[docs]` installs Sphinx, MyST, and (optionally) Furo without conflicts.
    
-  `nox -s docs` produces HTML in `docs/_build/html` on a clean clone.
    
-  Opening `docs/_build/html/index.html` shows “Hello, Docs!”.
    

---

#### Work items

- **ci(docs): add GitHub Pages workflow**  
    `.github/workflows/docs.yml`
    
    ```yaml
    name: docs               # lowercase workflow name
    on:
      push:
        branches: [main]
      push:
        tags: ['*']
    jobs:
      build:                 # lowercase job id
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: ./bootstrap.sh        # sets up uv & deps
          - run: nox -s docs
          - uses: peaceiris/actions-gh-pages@v4
            with:
              publish_dir: docs/_build/html
              publish_branch: gh-pages
    ```
    
- **docs(readme): add live docs badge/link**  
    `[![docs](https://img.shields.io/badge/docs-live-blue)](https://<org>.github.io/<repo>/)`
    
- **ops(pages): enable GitHub Pages** (manual) — set source to `gh-pages / (root)`.
    

#### Acceptance checklist

-  GitHub Actions job succeeds on push to `main` and any tag.
    
-  `gh-pages` branch contains generated HTML.
    
-  `https://<org>.github.io/<repo>/` shows _Hello, Docs!_ page.
    
-  README has live-docs badge and `nox -s docs` command.
    

---

### Dependencies

p1 depends on completion and merge of p0.

---

### Commit Guidelines (examples)

|Phase|Commit header|Notes|
|---|---|---|
|p0|**build(deps): add Sphinx + MyST (+Furo optional)**|extras in `pyproject.toml`|
|p0|**feat(docs): scaffold minimal Sphinx tree**|adds `conf.py`, `index.md`|
|p0|**chore(nox): add docs session**|enables `nox -s docs`|
|p0|**docs(readme): add local docs build command**|README|
|p1|**ci(docs): add GitHub Pages workflow**|workflow file|
|p1|**docs(readme): add live docs badge**|README|

Each phase (p0, p1) is self-contained: reviewers can evaluate local doc generation before considering CI, and deployment logic without revisiting scaffolding.
