### ISSUE TITLE
Integrate Python Coverage Comment GitHub Action

### ISSUE THREAD

**Issue by plva** [plva/econexyz#63]
### Goal

Automate test-coverage feedback without leaving GitHub:

* PRs receive an updated comment showing total % and per-file deltas
* The default branch hosts a badge (`coverage.svg`) and a browsable HTML report — all stored inside the repo (no external SaaS)

---

### Scope of work

1. **Add runtime dependency**

   * Ensure `coverage` and `pytest-cov` are already in the `[tool.uv.dependency-group.test]` set.
   * Update the existing Nox `tests` session to generate a `.coverage` file and an XML/HTML report:

     ```python
     session.run(
         "pytest",
         "--cov=yourpackage",
         "--cov-report=xml",
         "--cov-report=html",
         "--cov-report=term",
     )
     ```

2. **Create the GitHub Action workflow**
   Path: `.github/workflows/coverage.yml`

   ```yaml
   name: coverage
   on:
     pull_request:
     push:
       branches: [ main ]

   jobs:
     coverage:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-python@v5
           with: {python-version: '3.12'}
         - run: ./bootstrap.sh nox -s tests
         - name: Python Coverage Comment
           uses: py-cov-action/python-coverage-comment-action@v3
           with:
             badge-title: coverage
             github-token: ${{ secrets.GITHUB_TOKEN }}
   ```

   * The Action automatically detects the `.coverage` file in the workspace.
   * No extra secrets are required beyond the default `GITHUB_TOKEN`.

3. **Enable badge branch**
   The Action will create (or update) a branch named `gh-pages-coverage` (default); no manual setup needed.

4. **README badge**
   Add at the top of `README.md`:

   ```markdown
   ![coverage](https://raw.githubusercontent.com/<org>/<repo>/gh-pages-coverage/coverage.svg)
   ```

   (replace `<org>` and `<repo>`)

5. **Nox & CI**

   * The test session already produces `.coverage`; no additional CI changes needed.
   * Keep HTML output under `htmlcov/` — the Action will publish it.

---

### Edge cases & tips

* For private repos the HTML report is not hosted; only the badge and JSON files are committed.
* If your default branch isn’t `main`, change the `push.branches` filter.
* To avoid badge-spam on early drafts, you can enable the workflow once test coverage > 0 %.
* The badge branch does **not** count against Actions minutes (it’s a simple git push).

---

### Acceptance checklist

* [ ] Running `nox -s tests` locally leaves a `.coverage` file and `htmlcov/index.html`.
* [ ] Opening a PR triggers a coverage comment that updates on each push.
* [ ] Merging to `main` creates (or updates) `gh-pages-coverage` with `coverage.svg`.
* [ ] The badge renders in the README on GitHub.
* [ ] Failing coverage thresholds cause the Action to mark the step `failure` when configured later.
