### ISSUE TITLE
Add Bandit Static Security Scan

### ISSUE THREAD

**Issue by plva** [plva/econexyz#83]
### Goal

Detect common Python security issues (injection, weak hashing, subprocess misuse, etc.) during development and CI by integrating **Bandit** into the tooling stack.

---

### Work items

1. **Dependency**

   ```bash
   uv pip install --save-dev bandit
   ```

2. **Pre-commit hook**
   Add to `.pre-commit-config.yaml`

   ```yaml
   -   repo: https://github.com/PyCQA/bandit
       rev: "1.7.7"
       hooks:
         - id: bandit
           name: Bandit security scan
           args: ["-r", "src/", "-ll"]      # recursive, low-severity and up
           language_version: python3
   ```

3. **Nox session**

   ```python
   @nox.session(reuse_venv=True)
   def security_scan(session):
       session.install("bandit")
       session.run("bandit", "-r", "src/", "-ll")  # fail on medium/high issues
   ```

4. **Justfile helper**

   ```
   bandit:
       nox -s security_scan
   ```

5. **CI integration**
   Insert after lint step:

   ```yaml
   - name: Bandit security scan
     run: just bandit
   ```

6. **Documentation**
   *README → Security*

   ```
   just bandit   # run static security checks locally
   ```

---

### Acceptance checklist

* [ ] `uv pip install -e .[dev]` installs Bandit successfully.
* [ ] `just bandit` scans `src/` and exits 0 on a clean codebase.
* [ ] Introducing a known issue (e.g., `subprocess.call(input)`) causes Bandit to flag and CI to fail.
* [ ] Pre-commit blocks commits that introduce new Bandit violations.
* [ ] README documents the Bandit command.
