### ISSUE TITLE
Introduce Hatch Workspaces for Future Monorepo Expansion

### ISSUE THREAD

**Issue by plva** [plva/econexyz#88]
### Goal

Prepare the repository to evolve from a single package into a lightweight monorepo—multiple interdependent Python packages managed by **Hatch**.
Hatch will coexist with our current `uv` workflow: `uv` still resolves and installs dependencies, while Hatch handles package layouts, scripts, and versioning inside a unified `pyproject.toml`.

---

### Work items

1. **Install Hatch**
   *Add to dev dependencies*
   `uv pip install --save-dev hatch hatchling`

2. **Convert current project to a Hatch-managed package**

   * In `pyproject.toml`, add

     ```toml
     [build-system]
     requires = ["hatchling"]
     build-backend = "hatchling.build"

     [tool.hatch.metadata]
     allow-direct-references = true

     [tool.hatch.version]
     source = "commitizen"        # keeps compatibility with cz bump
     ```
   * Move existing package under `packages/core/yourpackage` (or leave at root for now).

3. **Enable workspaces**
   Append to `pyproject.toml`

   ```toml
   [tool.hatch.envs.default]
   dependencies = ["-r requirements.txt"]

   [tool.hatch.workspaces]
   default = ["packages/*"]
   ```

4. **Add a sample secondary package**

   * `packages/utils/yourutils/__init__.py` with one function.
   * Minimal `packages/utils/pyproject.toml` that sets `name = "yourutils"` under `[project]`.

5. **CLI helpers**

   * Add Justfile recipe `hatch build` → `hatch build -w` (build all workspace packages).
   * Add Nox session `hatch-test` that sets `HATCH_ENV=testing` and runs `hatch run +py312:pytest`.

6. **CI integration**

   * Insert a step in main workflow:
     `just hatch build` (asserts all packages build).
   * Ensure `uv pip sync` installs editable versions of every workspace package (`uv pip install -e packages/utils` etc.) or rely on Hatch’s dev env inside the Nox `hatch-test` session.

7. **Documentation**

   * README section “Monorepo layout via Hatch” explaining:
     • Add new package under `packages/<name>/` with its own `pyproject.toml`
     • Hatch commands (`hatch build`, `hatch run`) operate on all workspace packages.

---

### Acceptance checklist

* [ ] `uv pip install -e .[dev]` brings in Hatch.
* [ ] `hatch build -w` succeeds, producing wheels for `yourpackage` and `yourutils`.
* [ ] `just hatch build` runs in CI and passes.
* [ ] Adding `packages/demo/` with a minimal `pyproject.toml` causes Hatch to include it automatically.
* [ ] README documents the workspace pattern and basic Hatch commands.
