### ISSUE TITLE
Add Trivy Container Scan & SBOM Generation

### ISSUE THREAD

**Issue by plva** [plva/econexyz#89]
### Goal

Scan the Docker image for OS-level and Python package CVEs on every build and publish a CycloneDX Software Bill of Materials (SBOM) artifact for downstream consumers.

---

### Work items

1. **CI workflow update**
   *In the existing `docker.yml` (image-build) job, add two steps after the `docker build` / push:*

   ```yaml
   - name: Scan image with Trivy
     uses: aquasecurity/trivy-action@0.13.0
     with:
       image-ref: ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}
       format: table
       exit-code: 1            # fail job on high/critical CVEs
       ignore-unfixed: true    # only report fixes that exist

   - name: Generate CycloneDX SBOM
     uses: aquasecurity/trivy-action@0.13.0
     with:
       image-ref: ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }}
       format: cyclonedx
       output: sbom.cdx.json
       exit-code: 0            # always succeed; SBOM creation shouldn’t block

   - name: Upload SBOM artifact
     uses: actions/upload-artifact@v3
     with:
       name: sbom-${{ github.sha }}
       path: sbom.cdx.json
   ```

2. **Local developer convenience**
   Add a Justfile recipe:

   ```
   scan-image tag=latest:
       trivy image ghcr.io/<org>/<repo>:{{tag}}
   ```

   Document installing Trivy locally via `brew install trivy` or `scoop install trivy`.

3. **False-positive handling**
   Commit `.trivyignore` (empty for now) and note in README how to add CVE IDs with justification.

4. **Documentation**
   *README*

   * “CI blocks merges if High/Critical CVEs are detected in the container.”
   * “Generated SBOM (CycloneDX) is downloadable from each workflow run artefacts.”

5. **ADR note**
   Append a paragraph to `000X-container-security.md` explaining why Trivy was selected (multi-ecosystem scanning, SBOM output, no extra infra).

---

### Acceptance checklist

* [ ] `docker build` workflow now includes Trivy scan and SBOM steps.
* [ ] A failing test case (e.g., base image downgraded to a vulnerable tag) causes the CI job to fail.
* [ ] Successful runs attach `sbom-<SHA>.cdx.json` artefact.
* [ ] `just scan-image tag=latest` works locally after installing Trivy.
* [ ] README explains security gate and SBOM download location.
