### ISSUE TITLE
Integrate Gitleaks Secret-Scanning in Hooks and CI

### ISSUE THREAD

**Issue by plva** [plva/econexyz#90]
### Goal
Stop secrets from ever landing in the repo by scanning both locally (pre-commit) and in CI, with a single extra job called `secret-scan`.

---

#### Phase P0 – Local Hooks & Tooling (pre-CI)
1. **Dev dependency**  
```bash
   uv tool install gitleaks
````

2. **Pre-commit hook** – extend `.pre-commit-config.yaml`

   ```yaml
   - repo: https://github.com/gitleaks/gitleaks
     rev: v8.18.2            # pin for reproducibility
     hooks:
       - id: gitleaks
         name: Gitleaks secret scan
         stages: [commit, push]
         args: ["--verbose", "--redact"]
   ```

3. **Developer guidance & docs**
   *Add to `README.md`*

   ```
   Secrets are blocked by Gitleaks. False positives? Add an allow-rule to .gitleaks.toml with a justification.
   ```

   Local scan command:

   ```bash
   uv tool run gitleaks detect --source . --redact
   ```

---

#### Phase P1 – CI Enforcement (post-CI)

1. **Add `secret-scan` job** to the existing workflow (`ci.yml` or similar):

   ```yaml
   name: ci
   on: [push, pull_request]

   jobs:
     secret-scan:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: gitleaks scan
           uses: gitleaks/gitleaks-action@v2
           with:
             config-path: .gitleaks.toml   # omit if file absent
             fail: true                   # block on any leak

     tests:
       needs: secret-scan
       runs-on: ubuntu-latest
       steps:
         # existing test steps here...
   ```

2. **Custom rules (optional)**
   *Create `.gitleaks.toml` only when needed to whitelist false positives or add org-specific patterns.*

---

#### P0

* [ ] `uv tool install gitleaks` works; `gitleaks version` prints locally.
* [ ] Committing a mock secret (`AWS_ACCESS_KEY_ID=AKIA...`) is blocked by pre-commit.
* [ ] Removing the secret allows the commit to proceed.
* [ ] README contains secret-scanning docs and remediation steps.

#### P1

* [ ] CI job **secret-scan** runs on every push/PR before **tests**.
* [ ] Injecting a mock secret via GitHub UI causes the pipeline to fail.
* [ ] Removing the secret lets the pipeline pass.
* [ ] `.gitleaks.toml` suppresses a known false positive and the job passes, with the rule documented.

---

### Optional / Future Work

* Nightly scheduled `secret-scan` to catch retroactive leaks in long-lived branches.
* Severity labeling in the PR comment (e.g., secret type) for faster triage.
* Integration with GitHub’s built-in secret-scanning API to de-duplicate alerts.
