### ISSUE TITLE
Integrate Gitleaks Secret-Scanning in Hooks and CI

### ISSUE THREAD

**Issue by plva** [plva/econexyz#94]
### Goal

Block API keys, credentials, and other sensitive tokens from ever reaching the repository—whether they’re committed locally or pushed via GitHub’s web UI.
Gitleaks must run:

1. **Locally** via pre-commit hooks (commit and push stages)
2. **In CI** on every PR and main-branch push

---

### Work items

1. **Install Gitleaks as a dev tool**

   ```bash
   uv tool install gitleaks         # managed by uv’s toolchain
   ```

2. **Pre-commit integration**
   Add to `.pre-commit-config.yaml`:

   ```yaml
   - repo: https://github.com/gitleaks/gitleaks
     rev: v8.18.2
     hooks:
       - id: gitleaks
         name: Gitleaks secret scan
         stages: [commit, push]
         args: ["--verbose", "--redact"]
         language_version: python3
   ```

3. **CI workflow step**
   Append to the primary GitHub Actions workflow *before* tests:

   ```yaml
   - name: Gitleaks scan
     uses: gitleaks/gitleaks-action@v2
     with:
       config-path: .gitleaks.toml   # optional; omit if default rules suffice
       fail: true                    # fail job on any detected secret
   ```

4. **Custom rules / allow-list** (optional)

   * Commit an empty `.gitleaks.toml` now.
   * Document how to add FALSE\_POSITIVE rules with justification comments.

5. **Justfile helper**

   ```
   secrets:
       uv tool run gitleaks detect --source . --redact
   ```

6. **Documentation**

   * README “Security” section:

     * “Secrets are blocked by Gitleaks; run `just secrets` locally.”
     * Steps to handle false positives.

---

### Acceptance checklist

* [ ] `uv tool install gitleaks` succeeds; `gitleaks version` prints locally.
* [ ] Attempting to commit a fake secret (`AWS_SECRET_ACCESS_KEY=ABCD...`) is blocked by the pre-commit hook.
* [ ] Pushing the same secret via GitHub UI causes the CI Gitleaks step to fail.
* [ ] README documents the secret-scanning workflow and false-positive mechanism.
